name: build deb

on:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: gitee-sync

      - name: Set up dependencies
        run: |
          sudo apt install xsel wl-clipboard build-essential cmake debhelper tree -y

      - name: deb
        run: |
          dpkg-buildpackage -S -nc --no-sign
          dpkg-buildpackage -us -uc -b
          dh clean
          # 移动上层目录的 deb 文件到当前工作目录
          mv ../*.deb .

      - name: Upload DEB package
        uses: actions/upload-artifact@v4
        with:
          name: faqyh-package
          path: "*.deb"
          retention-days: 7