name: Gitee to GitHub Sync

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 运行一次，主人可以根据需要调整时间
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取所有历史记录
          ref: gitee-sync  # 确保检出 gitee-sync 分支

      - name: Set up Git
        run: |
          git config --global user.name "zhangyiming748"
          git config --global user.email "zhangyiming748@gmail.com"

      - name: Pull from Gitee and Push to GitHub
        run: |
          git remote add gitee https://gitee.com/openkylin/faqyh.git
          git fetch gitee master
          git reset --hard gitee/master
          git push origin gitee-sync --force
